
package com.nam2;

import com.nam.WebService42;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebService42ImplService", targetNamespace = "http://nam.com/", wsdlLocation = "http://localhost:4242/wss/hello?wsdl")
public class WebService42ImplService
    extends Service
{

    private final static URL WEBSERVICE42IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICE42IMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICE42IMPLSERVICE_QNAME = new QName("http://nam.com/", "WebService42ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:4242/wss/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICE42IMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICE42IMPLSERVICE_EXCEPTION = e;
    }

    public WebService42ImplService() {
        super(__getWsdlLocation(), WEBSERVICE42IMPLSERVICE_QNAME);
    }

    public WebService42ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICE42IMPLSERVICE_QNAME, features);
    }

    public WebService42ImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICE42IMPLSERVICE_QNAME);
    }

    public WebService42ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICE42IMPLSERVICE_QNAME, features);
    }

    public WebService42ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebService42ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebService42
     */
    @WebEndpoint(name = "WebService42ImplPort")
    public WebService42 getWebService42ImplPort() {
        return super.getPort(new QName("http://nam.com/", "WebService42ImplPort"), WebService42.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebService42
     */
    @WebEndpoint(name = "WebService42ImplPort")
    public WebService42 getWebService42ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://nam.com/", "WebService42ImplPort"), WebService42.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICE42IMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICE42IMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICE42IMPLSERVICE_WSDL_LOCATION;
    }

}
